# Generated by Django 4.2.9 on 2024-01-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0002_cryptouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptouser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cryptouser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cryptouser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='cryptouser',
            name='username',
        ),
    ]
