# Generated by Django 4.2.9 on 2024-01-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoapp', '0010_kyc_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='approved',
            new_name='verified_user',
        ),
        migrations.AddField(
            model_name='cryptouser',
            name='is_kyc_done',
            field=models.BooleanField(default=False),
        ),
    ]
